name: Pipeline CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Vérification du code source
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Exécuter les tests
        run: |
          pytest test_liste_de_taches.py
